return {}
-- return {
--   {
--     "telescope.nvim",
--     dependencies = {
--       -- fzf extension
--       {
--         "nvim-telescope/telescope-fzf-native.nvim",
--         build = "make",
--       },
--       -- project management
--       {
--         "ahmedkhalf/project.nvim",
--         opts = {
--           manual_mode = true,
--           detection_methods = { "pattern" },
--           patterns = { "package.json", ".git" },
--         },
--         event = "VeryLazy",
--         config = function(_, opts)
--           require("project_nvim").setup(opts)
--           require("lazyvim.util").on_load("telescope.nvim", function()
--             require("telescope").load_extension("projects")
--           end)
--         end,
--         keys = {
--           { "<leader>fp", "<Cmd>Telescope projects<CR>", desc = "Projects" },
--         },
--       },
--     },
--     config = function()
--       require("telescope").setup({
--         extensions = {
--           fzf = {
--             fuzzy = true,
--             override_generic_sorter = true,
--             override_file_sorter = true,
--             case_mode = "smart_case",
--           },
--         },
--       })
--       require("telescope").load_extension("fzf")
--     end,
--   },
--
--   {
--     "goolord/alpha-nvim",
--     optional = true,
--     opts = function(_, dashboard)
--       local button = dashboard.button("p", " " .. " Projects", ":Telescope projects <CR>")
--       button.opts.hl = "AlphaButtons"
--       button.opts.hl_shortcut = "AlphaShortcut"
--       table.insert(dashboard.section.buttons.val, 4, button)
--     end,
--   },
--   {
--     "echasnovski/mini.starter",
--     optional = true,
--     opts = function(_, opts)
--       local items = {
--         {
--           name = "Projects",
--           action = "Telescope projects",
--           section = string.rep(" ", 22) .. "Telescope",
--         },
--       }
--       vim.list_extend(opts.items, items)
--     end,
--   },
--   {
--     "nvimdev/dashboard-nvim",
--     optional = true,
--     opts = function(_, opts)
--       local projects = {
--         action = "Telescope projects",
--         desc = " Projects",
--         icon = " ",
--         key = "p",
--       }
--
--       projects.desc = projects.desc .. string.rep(" ", 43 - #projects.desc)
--       projects.key_format = "  %s"
--
--       table.insert(opts.config.center, 3, projects)
--     end,
--   },
-- }
